---
language: python

python:
  - "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i ubuntu.box site.yml --syntax-check
  - ansible-playbook -i centos.box site.yml --syntax-check
  - ansible-playbook -i fedora.box site.yml --syntax-check
