- name: update a server
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: upgrade a server
  apt: upgrade=full
  when: ansible_os_family == 'Debian'

- name: upgrade all packages
  yum: name=* state=latest
  when: ansible_os_family == 'RedHat'