---
dependencies:
  - { role: groonga-repo/redhat, when: ansible_distribution == 'CentOS' }
  - { role: groonga-repo/fedora, when: ansible_distribution == 'Fedora' }
  - { role: groonga-repo/ubuntu, when: ansible_distribution == 'Ubuntu' }
